### ISSUE TITLE
packages required when using pyodideUrl mount option

### ISSUE THREAD

**Issue by hoishing** [whitphx/stlite#1007]
I tried to provide my own pyodide in order to minimize the first loading time using the `pyodideUrl` mount option. If I use the full distribution it's fine. However if I use the core pyodide, I will get module not found error for the following packages:

- micorpip
- packaging
- typing_extensions
- protobuf
- cachetools

after copying these packages to the core pyodide folder everything run fine again.

I would like to ask, are these packages all I needed when using my own pyodide distribution? I seem can't find any documentation about it. Thanks ~

**Comment by whitphx** [comment]
Hi,

> are these packages all I needed when using my own pyodide distribution?

Yes. `micropip` is used to install all the required packages including `streamlit`, and other packages are required by the `streamlit` package.

So, I recommend to serve the full distribution.
Even if the full ver. is used, only required packages are loaded to the stlite app, so it shouldn't affect the initial loading time anyway.

I will update the doc about this.

**Comment by hoishing** [comment]
thanks a lot 🙏
