### ISSUE TITLE
Can't use st.navigation if any pages use top-level async

### ISSUE THREAD

**Issue by intelligentestech** [whitphx/stlite#1109]
It seems like the pages.py in Streamlit does not await calls to run a page when using st.navigation, which means that you can't use any async calls in any pages if you use st.navigation

**Comment by whitphx** [comment]
Thank you, I confirmed and will fix it.

**Comment by whitphx** [comment]
0.67.1 should have fixed it, thanks!

**Comment by intelligentestech** [comment]
Works now, thanks!
