### ISSUE TITLE
Security audit of Gradio: relevant to stlite?

### ISSUE THREAD

**Issue by LukeAFullard** [whitphx/stlite#1156]
Just wondering if the security audit of Gradio is relevant for stlite?

https://github.com/trailofbits/publications/blob/master/reviews/2024-10-huggingface-gradio-securityreview.pdf

**Comment by whitphx** [comment]
Thanks, I think it's not the case.
* Those security audits are specific to Gradio's source code
* Some reported vulnerabilities are not the problem in the Stlite environment because it's sandboxed in the web browser and is never shared between normal users and attackers.

**Comment by whitphx** [comment]
Notifying the report to the upstream [`streamlit/streamlit`](https://github.com/streamlit/streamlit) project may be a good action.
