### ISSUE TITLE
More Control Over Loaded Packages

### ISSUE THREAD

**Issue by aghasemi** [whitphx/stlite#127]
Hi,

I do not use someof these packages, but they are loaded nevertheless (e.g. PIL):

![image](https://user-images.githubusercontent.com/7351535/185646426-72f2db57-a536-4220-8ac1-6de231757a37.png)

 Is there a way, or a plan to implement a way, to have more control over what packages are loaded?

**Comment by whitphx** [comment]
No.

I think these are the dependencies of `streamlit` package (or the deps of the deps, ...) such as https://github.com/streamlit/streamlit/blob/1.12.0/lib/setup.py#L38-L66
so these packages must be installed for streamlit to run.

Formally, it is possible to prevent these packages from being installed with the the micropip API by controlling the `deps` flag of [`micropip.install()`](https://pyodide.org/en/stable/usage/api/micropip-api.html#micropip.install), but I think it's useless.
