### ISSUE TITLE
Set up the infrastructure for the sharing service

### ISSUE THREAD

**Issue by whitphx** [whitphx/stlite#204]
# Requirements
* Functionality coverage for the following service plans
* Access performance
  * https://bejamas.io/compare/vercel-vs-cloudflare-pages/
  * CDN coverage
  * Zero cold start
* Commercial use
* Analytics
* Developer experience
  * CI/CD, deployment preview

# Top page
`www.stlite.net`: Redirects to apex
`stlite.net`
`stlite.net/sharing`: About sharing
`stlite.net/bundler`: About bundler

* Static pages only

# Sharing service
#68 #104 
### Step1 
The source code and requirements data are encoded in the URL hash.

#### URL:
* `share.stlite.net/#code=xxx`: Sharable app
  * Use the URL hash, not the query string to avoid sending the data to the server.
* ~~`share.stlite.net/edit#code=xxx`~~ `edit.share.stlite.net/#code=xxx`: Editor with iframe that embeds the sharable app
  * All the paths (`share.stlite.net/*`) should be preserved for MPA routing? -> Fixed in #212
#### Required technologies:
* Static site hosting

### Step2:
The source code and requirements data are stored in the server-side data store and access it with an ID.

#### URL:
* `share.stlite.net/<id>`: Sharable app
* `edit.share.stlite.net/<id>`: Editor
#### Required technologies:
* Server-side KVS mapping ID to code
  * Cloudflare KV
    * Value: up to 2MB
* SSR or something like it
  * If we use Cloudflare Workers, the code can be dynamically injected into the HTML, so SSR like NextJS is not needed.

### Step3 (Subdomain & Service Worker):
In addition to Step 2, the ID is represented by subdomain. Service Worker is introduced.

* `<id>.share.stlite.net`
* `<id>.edit.share.stlite.net`: Editor

### Step4 (Authentication)
User authentication is introduced for access control.

Required technologies:
* Auth

# Bundler API
#69 

* `bundle.stlite.net/...`
  * Stateless?
    * Just called from the sharing service frontend with full code
#### Required technologies:
* Auth
  * Behind Cloudflare Workers as API gateway?

---

# Candidates
* Vercel
* Cloudflare Pages
* Render
* GitHub pages
* Netlify
* Firebase
* fly-io
* Adaptable

Comparison: https://docs.google.com/spreadsheets/d/1wL55Nz9PXIPe8Zj79XDgb_5xWdzWHz-WcqAs_bn1n70/edit#gid=0

According to the features, Vercel, Cloudflare Pages and Render look good.
Among them, due to the performance, Vercel and Cloudflare Pages look good.
Among them, due to the cost, Cloudflare Pages look good.

**Comment by aghasemi** [comment]
> The source code and requirements data are encoded in the URL param.
> 
> URL:
> 
> share.stlite.net/?code=xxx: Sharable app
> share.stlite.net/edit?code=xxx: Editor with iframe that embeds the sharable app
> Required technologies:
> Static site hosting

Oh! I'm writing the exact same thing at the moment :D

**Comment by whitphx** [comment]
We have done it on Cloudflare Workers.

**Comment by whitphx** [comment]
Next -> #387
