### ISSUE TITLE
Sharing app to load the app script from a GitHub repo

### ISSUE THREAD

**Issue by whitphx** [whitphx/stlite#256]

**Comment by napoles-uach** [comment]
I did this example to call a github url, but for some reason it is not working now :(

https://github.com/napoles-uach/readurl/blob/main/index.html

What could be the reason?

**Comment by whitphx** [comment]
The stlte script URL has been changed (the old URL was fragile).
Rewrite the script tag's `src` URL with the one described in the current README.

**Comment by napoles-uach** [comment]
Yes, it works! Thanks!

<img width="377" alt="msedge_1KClsIeoW7" src="https://user-images.githubusercontent.com/30182239/190527768-5ec7c0cd-e236-41b4-9152-1fd8fe12a417.png">

**Comment by whitphx** [comment]
stlite sharing now supports loading the source code from a URL.

* Simply pass the URL as a URL hash:
https://share.stlite.net/#https://github.com/napoles-uach/test/blob/main/app.py

* If installing requirements is necessary, use query parameter-like syntax as below. `#url=<Script URL>?req=<Package Name>`. For multiple requirements, use the `req=` key for each.
https://share.stlite.net/#url=https://github.com/whitphx/stlite-sample/blob/main/opencv-image-processing.py&req=opencv-python&req=matplotlib
