### ISSUE TITLE
Bad message format: Cannot handle type "refHash".

### ISSUE THREAD

**Issue by sminot** [whitphx/stlite#282]
When I change the values used in an app, and then change them back to the values I used before, I get the error message:

![image](https://user-images.githubusercontent.com/5215560/191369147-d4837385-dcaa-4a5e-9ce0-f574ba86fb02.png)

You can see an example here:
https://fredhutch.github.io/stlite-template

The code used to generate that site is here:
https://github.com/FredHutch/stlite-template

**Comment by whitphx** [comment]
This should be fixed with `@stlite/mountable@0.7.0` and the current [stlite sharing](https://edit.share.stlite.net/)
