### ISSUE TITLE
Electron app bundler

### ISSUE THREAD

**Issue by whitphx** [whitphx/stlite#301]
Rel #69 

1. Publish `@stlite/desktop` with its `./build` directory in which the built JS app code is included. #314 
2. Publish `@stlite/stlite-kernel` with the wheels that is needed in the following bundling steps. #302

Then, the Streamlit app creator who wants to bundle the app with Electron will do the following steps.
1. Create an electron app project that only contains `package.json` looking like below. It is extracted from the `packge.json` in `@stlite/desktop` only with the `electron-builder` configs and `@stlite/stlite-kernel` dependency, from which the wheels are loaded at the bundle time.
```json
{
  "name": "xxx",
  "version": "xxx",
  "main": "./build/electron/main.js",
  "dependencies": {},
  "scripts": {
    "pack": "electron-builder --dir",
    "dist": "electron-builder",
    "postinstall": "electron-builder install-app-deps"
  },
  "build": {
    "appId": "your.id",
    "mac": {
      "category": "your.app.category.type"
    },
    "productName": "xxx",
    "extends": null,
    "files": [
      "build/**/*"
    ],
    "directories": {
      "buildResources": "assets"
    }
  },
  "devDependencies": {
    "electron": "20.2.0",
    "electron-builder": "^23.3.3"
  }
}
```
2. Copy the `./build` directory from `@stlite/desktop`.
3. Run `./bin/dump_snapshot.ts` from `@stlite/desktop` (this scripts needs the wheel files from `@stlite/stlite-kernel`).
4. Run `yarn dist`.

In the future, creating the project with `package.json` above can be automated like `yarn create`.

**Comment by whitphx** [comment]
At this point, use https://github.com/whitphx/stlite/pull/322#issuecomment-1267349510

**Comment by whitphx** [comment]
### Current version of the stlite desktop app development
Repo: https://github.com/whitphx/stlite-desktop-example

1. Create a new NPM project with the following `package.json`. 
```json
{
  "name": "xxx",
  "version": "0.1.0",
  "main": "./build/electron/main.js",
  "scripts": {
    "dump": "dump-stlite-desktop-artifacts",
    "serve": "NODE_ENV=\"production\" electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder",
    "postinstall": "electron-builder install-app-deps"
  },
  "build": {
    "files": [
      "build/**/*"
    ],
    "directories": {
      "buildResources": "assets"
    }
  },
  "devDependencies": {
    "@stlite/desktop": "*",
    "electron": "20.2.0",
    "electron-builder": "^23.3.3",
    "node-fetch": "2",
    "pyodide": "^0.21.3"
  }
}
```
2. Run `npm install` or `yarn install`.
3. Create `streamlit_app` directory.
    * Any directory name can be used here.
4. Create  `streamlit_app/streamlit_app.py`.
    * Change the directory name if you used a different name in the previous step.
5. Write your Streamlit app code  in  `streamlit_app/streamlit_app.py`. You can create `pages/*.py` for MPA if necessary.
4. Run `yarn dump streamlit_app`. If some packages are needed, use `-r` option like `yarn dump streamlit_app -r <PackageName1> ... <PackageNameN>`.
5. Run `yarn serve` for preview. Run `yarn dist` for packaging.

**Comment by whitphx** [comment]
TODO: Automate scaffolding.

**Comment by blackary** [comment]
FYI, I get this when trying to open the dmg on my M1 mac 
<img width="251" alt="image" src="https://user-images.githubusercontent.com/4040678/194136272-27c49f09-eda1-48d6-981b-df1f054366bb.png">

**Comment by blackary** [comment]
When I built my own locally, it worked on the first run, but when I closed it (with the x) and opened it again, I got this error 
<img width="235" alt="image" src="https://user-images.githubusercontent.com/4040678/194138888-a608da0a-b046-4aa2-a25d-ee4e22e376eb.png">

**Comment by whitphx** [comment]
@blackary Thank you for the report!

**Comment by whitphx** [comment]
@blackary I don't know why it did not work (it was built on my local machine and uploaded manually to the GitHub release page).
However I set up a different build and release flow on the CI/CD and created new files: https://github.com/whitphx/stlite-desktop-example/releases/tag/v0.2.0

**Comment by blackary** [comment]
@whitphx Thanks! I installed the new dmg, and it installed fine, but when it opens on my machine, it shows the loading bar briefly, then goes to a blank page 
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/4040678/194388945-c9102d6c-8890-4a4e-ba70-eada7bd7de60.png">

**Comment by mkisono** [comment]
@whitphx 
> ### Current version of the stlite desktop app development

I followed the steps and it's working fine on my mac.

When I run the following code as `strreamlit_app.py`, the progress bar didn't actually "progress". It just showed the end result. Is this by design or limitation?

```
import time
import streamlit as st

my_bar = st.progress(0)

for percent_complete in range(100):
    time.sleep(0.1)
    my_bar.progress(percent_complete + 1)
```

**Comment by whitphx** [comment]
@blackary Thanks,
Can you please tell if there are any errors on the console by opening the dev console from the menu as below?

<img width="1351" alt="View_と_Menubar_と_streamlit_app_·_Streamlit" src="https://user-images.githubusercontent.com/3135397/194506916-5464822a-29eb-4bc2-ba09-7b999ba1da34.png">

**Comment by whitphx** [comment]
@mkisono Thank you for trying it out, and 
> it's working fine on my mac.

it was a great report :)

---
> It just showed the end result. Is this by design or limitation?

it looks like the known issue as https://github.com/whitphx/stlite/issues/34#issuecomment-1202167681 ; `time.sleep()` does no-op on Pyodide runtime (https://github.com/pyodide/pyodide/issues/2354).
https://github.com/whitphx/stlite/issues/64 may also be the related topic.

**Comment by blackary** [comment]
> @blackary Thanks,
> Can you please tell if there are any errors on the console by opening the dev console from the menu as below?

@whitphx I gave that a try, and now am unable to reproduce the blank page I was getting 🤷

**Comment by whitphx** [comment]
I will close this issue.
The next TODOs have been created as separate issues.

**Comment by weissenbacherpwc** [comment]
is this still working or is there an update on how to convert a streamlit app to .exe?

**Comment by ziggycross** [comment]
It is working @weissenbacherpwc , follow the instructions [here](https://www.npmjs.com/package/@stlite/desktop). You will need to use NPM so a small amount of JS knowledge is required.
