### ISSUE TITLE
How to install Python requirements with desktop app

### ISSUE THREAD

**Issue by chrieke** [whitphx/stlite#337]
Hi, love the dektop app feature, it could be fantastic to build shareable solutions for local-file heavy or sensitive apps. 

Can't figure out how to install library requirements for my streamlit app when building the desktop app via the [instructions](https://github.com/whitphx/stlite/blob/main/packages/desktop-cli/README.md). Is that supported? It seems that a few things like pandas etc. are installed by default. Would be great if it would automatically read the regular requirements.txt file?

**Comment by whitphx** [comment]
Thank you.

Yes, it is supported. See the first bullet point at the step 7. You can install the libraries with the `npm run dump` command and its `-r` option.
Sorry if it is hard to find. If you have some ideas to improve the instruction, please add it in your PR (#336).

>  Would be great if it would automatically read the regular requirements.txt file?

Thank you, that's a good idea. Let me consider the design.

**Comment by chrieke** [comment]
Saw that option but figured it would be for additional NPM packages etc. since it didn't seem to work for Python packages. Is this the correct syntax?

`npm run dump streamlit_app -r matplotlib`

**Comment by whitphx** [comment]
Oops, sorry the documentation is wrong.
For `npm`, the double hyphens are necessary to pass the parameters, so use the following one.
`npm run dump streamlit_app -- -r matplotlib`

**Comment by chrieke** [comment]
Awesome, that works, thank you! For some reason need to specify another matplotlib subdependency (cycler) but then it works. Thanks!
