### ISSUE TITLE
Missing Module error using stlite

### ISSUE THREAD

**Issue by seanbf** [whitphx/stlite#403]
Apologies - I'm relatively new to coding so I may be missing something obvious.

I have a streamlit app that works via the commanf line:
`python -m streamlit run streamlit_app.py` this also calls several other python files such as a separate `.py` file to "draw" the ui, another containing constants etc.

I believe this is where stlite app is falling over?

**What i expect to see**

![image](https://user-images.githubusercontent.com/83425701/203845886-8d6985b9-f99e-4a38-a09c-dc9294646210.png)

**stlite/electron app with debug enabled**

![image](https://user-images.githubusercontent.com/83425701/203845936-4f51947f-f965-45d4-bd98-224e5d3cfb5f.png)

I've tried to figure this out myself but im out of my depth looking at the internals of the tool/stlite.

"Folder layout" 
![image](https://user-images.githubusercontent.com/83425701/203846383-4a4c6297-d977-4f43-b882-d8c4c9405631.png)

**Comment by whitphx** [comment]
It seems to be a bug with multiple modules.
Thank you for reporting it and be patient for the fix.

**Comment by whitphx** [comment]
To investigate the problem,
1. Paste the error message both from the web page and the shell (if exists) as texts, not screenshots.
1. Share the entire app codebase that I can use to reproduce the problem on my local. It should be a "minimum reproducible sample" excluding files unnecessary to reproduce the bug.

Please read https://discuss.streamlit.io/t/using-streamlit-how-to-post-a-question-in-the-streamlit-forum/30960 for the details. It is a guideline written for the Streamlit forum, but meaningful for general tech posts.

**Comment by whitphx** [comment]
As a hint, please share the contents of the `build` directory just after running `yarn dump` or `npm run dump` in a text format copied from the shell).
