### ISSUE TITLE
Issues with requirements.txt functionality

### ISSUE THREAD

**Issue by kevinlinxc** [whitphx/stlite#406]
Hi, cool project, however, I have a few suggestions and questions.

1. You should mention that you need to pass -- to npm to use the -r option, e.g. `npm run dump streamlit_app -- -r requirements.txt`. This is not obvious to someone who doesn't use npm (me). 
2. You should ignore lines that start with # in requirements files, as pip recognizes these as comments
3. Is it possible to use an index url to bundle external packages too (normally would be pip install --index-url={company pypi} package_name

**Comment by whitphx** [comment]
Hi, thank you.

> 1.
> 2.

Makes sense. I will fix them.

> 3.

No.
The dump command simply calls [`micropip.install()`](https://pyodide.org/en/stable/usage/api/micropip-api.html#micropip.install) in its internals and it reads the packages only from the Pyodide repository and PyPI.
Instead, you can specify the wheel file URL directly in place of the package name to read it from non-standard hosts.
Please read the document about [`micropip.install()`](https://pyodide.org/en/stable/usage/api/micropip-api.html#micropip.install) for the details.

**Comment by kevinlinxc** [comment]
Is there a way to install from a local wheel path? For some packages, I could build a wheel, but not really upload them to anywhere to download via a URL.

**Comment by whitphx** [comment]
It is currently not supported, but it looks possible.
Can you create a feature request issue with a requirement description?

**Comment by whitphx** [comment]
Fixed since v0.19.1
