### ISSUE TITLE
Page not found: You have requested page /stlite, but no corresponding file was found in the app's pages/ directory. Running the app's main page.

### ISSUE THREAD

**Issue by whitphx** [whitphx/stlite#41]
* Access to https://whitphx.github.io/stlite/ (the playground app)
* Wait for the Streamlit app to be loaded
* The browser URL history is pushed to https://whitphx.github.io/
  * This is not HTTP redirect. It looks like history API manipulation
* At the same time, the following error dialog appears
  <img width="515" alt="スクリーンショット 2022-06-08 0 06 53" src="https://user-images.githubusercontent.com/3135397/172415202-dd315dbe-6042-4af3-a159-77f3128e25d7.png">
  ```
  Page not found
  You have requested page /stlite, but no corresponding file was found in the app's pages/ directory. Running the app's main page.
  ```

This seems to be derived from upgrading Streamlit to 1.10.0: #40 and its multipage app functionality.

**Comment by paulchicago74** [comment]
Just a note that this error is happening when I create my streamlit aop in a html file using the stlite.js. Same error on several browsers. I cleaned the cache but its still showing the message.

**Comment by whitphx** [comment]
Thanks!
stlite.js has not been taken care of.

**Comment by paulchicago74** [comment]
Thanks. Let me know when stlite.js is updated.
