### ISSUE TITLE
@stlite/desktop: Update pyodide version to 0.22.1

### ISSUE THREAD

**Issue by HUN220** [whitphx/stlite#475]
The next minor version of pyodide (0.22.*) has introduced a few additional packages including `gdal`, `fiona`, `geopandas` which are very handy for working with spatial data in streamlit. Is it possible to have @stlite/desktop use the latest version of pyodide which at the time of writing is version 0.22.1?

There are of course several breaking changes that come with this minor release. From the [pyodide changelog](https://pyodide.org/en/stable/project/changelog.html):
- **BREAKING CHANGE** build/library and build/sharedlibrary key in the meta.yaml spec are removed. Use build/type instead. [#3238](https://github.com/pyodide/pyodide/pull/3238)
- **BREAKING CHANGE** The source/md5 checksum field is not longer supported in meta.yaml files, use source/sha256 instead [#3079](https://github.com/pyodide/pyodide/pull/3079)
- **BREAKING CHANGE** pyodide_build.io.parse_package_config function is removed in favor of pyodide_build.MetaConfig.from_yaml [#3079](https://github.com/pyodide/pyodide/pull/3079)
- **BREAKING CHANGE** Unvendored the sqlite3 module from the standard library. Before sqlite3 was included by default. Now it needs to be loaded with pyodide.loadPackage or micropip.install. [#2946](https://github.com/pyodide/pyodide/pull/2946)
- **BREAKING CHANGE** The Pyodide Python package is installed into /lib/python3.10 rather than /lib/python3.10/site-packages. [#3022](https://github.com/pyodide/pyodide/pull/3022)
- **BREAKING CHANGE** The matplotlib HTML5 backends are now available as part of the [matplotlib-pyodide](https://github.com/pyodide/matplotlib-pyodide) package. If you use the default backend from Pyodide, no changes are necessary. However, if you previously specified the backend with matplotlib.use, the URL is now different. See [package readme](https://github.com/pyodide/matplotlib-pyodide) for more details. [#3061](https://github.com/pyodide/pyodide/pull/3061)
- **BREAKING CHANGE** The micropip package was moved to a separate repository [pyodide/micropip](https://github.com/pyodide/micropip). In addion to installing the version shipped with a given Pyodide release, you can also install a different micropip version from [PyPi](https://pypi.org/project/micropip/) with,

```
await pyodide.loadPackage('packaging')
await pyodide.loadPackage('<URL of the micropip wheel on PyPI>')
```
from Javascript. From Python you can import the Javascript Pyodide package,

```
import pyodide_js
```
and call the same functions as above. [#3122](https://github.com/pyodide/pyodide/pull/3122)
- **BREAKING CHANGE** The messageCallback and errorCallback argument to loadPackage and loadPackagesFromImports is now passed as named arguments. The old usage still works with a deprecation warning. [#3149](https://github.com/pyodide/pyodide/pull/3149)
- **BREAKING CHANGE** pyodide-cdn2.iodide.io is not available anymore. Please use https://cdn.jsdelivr.net/pyodide instead. [#3150](https://github.com/pyodide/pyodide/pull/3150).
- **BREAKING CHANGE** We don’t publish pre-built Pyodide docker images anymore. Note that ./run_docker --pre-built was not working for a while and it was actually equivalent to ./run_docker. If you need to build a single Python wheel out of tree, you can use the pyodide build command instead. See [our blog post](https://blog.pyodide.org/posts/0.21-release/#building-binary-wheels-for-pyodide) for more information. [#3342](https://github.com/pyodide/pyodide/pull/3342).

**Comment by whitphx** [comment]
Thank you for the request. I would set this as a top priority to do next. Please be patient for days.

**Comment by whitphx** [comment]
Dev notes:

> BREAKING CHANGE The Pyodide Python package is installed into /lib/python3.10 rather than /lib/python3.10/site-packages. https://github.com/pyodide/pyodide/pull/3022

This may affect `@stlite/desktop`. 

> BREAKING CHANGE The matplotlib HTML5 backends are now available as part of the [matplotlib-pyodide](https://github.com/pyodide/matplotlib-pyodide) package. If you use the default backend from Pyodide, no changes are necessary. However, if you previously specified the backend with matplotlib.use, the URL is now different. See [package readme](https://github.com/pyodide/matplotlib-pyodide) for more details. https://github.com/pyodide/pyodide/pull/3061

We should check the matplotlib availability.

**Comment by whitphx** [comment]
Please try 0.24.0.
