### ISSUE TITLE
sys.platform = ?

### ISSUE THREAD

**Issue by caleb-depotanalytics** [whitphx/stlite#518]
Hey,

This may be the expected behavior, but it is causing issues when trying to run pypyodbc (pure python pyodbc):

sys.platform is evaluating to "emscripten"

Is that expected?

### Steps to reproduce
* Create an stlite desktop app with this code:
```python
import streamlit as st
import sys
st.write(sys.platform)
```

**Comment by whitphx** [comment]
Yes, because stlite runs on Pyodide.
-> https://pyodide.org/en/stable/usage/faq.html#how-to-detect-that-code-is-run-with-pyodide
