### ISSUE TITLE
ModuleNotFoundError: No module named 'altair.vegalite.v4'

### ISSUE THREAD

**Issue by colasajee** [whitphx/stlite#560]
Get this error everytime with all stlite webapps. Even when trying the stlite demo examples. 

Seems to be an issue with Streamlit not being compatible with the recently released altair==5.0
I believe Stlite is loading the latest version of altair by default where as Streamlit supports altair version 4 and below  hence the issue.  Please see the Traceback below.

Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 357, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 2, in <module>
  File "/lib/python3.10/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/lib/python3.10/site-packages/streamlit/delta_generator.py", line 45, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py", line 36, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'

**Comment by aggieed97** [comment]
I started getting the same error the last few days on my app as well.  I don't use Altair so was trying to find some other fix for this but have been unsuccessful so far.

**Comment by colasajee** [comment]
I think stlite loads Altair library by default even where it's not being explicitly imported

**Comment by aggieed97** [comment]
FWIW, I updated the following 2 lines of code in my script, and my html/website works now:

`href="https://cdn.jsdelivr.net/npm/@stlite/mountable@0.31.0/build/stlite.css"`

`<script src="https://cdn.jsdelivr.net/npm/@stlite/mountable@0.31.0/build/stlite.js"></script>`

My original code was running on 0.26.0 and now is updated to 0.31.0 as seen above.

**Comment by niuguy** [comment]
@stlite/desktop upgrade to 0.31.0 solved this issue on my end

**Comment by whitphx** [comment]
Hi, thank you for the report.
This is a bug on original Streamlit and `streamlit<=1.19.0` has been affected by the release of Altair v5.
`stlite` has upgraded its internal Streamlit version from `1.19.0` to `1.21.0` since [`0.31.0`](https://github.com/whitphx/stlite/blob/main/CHANGELOG.md#0310---2023-04-13), so using this version solves the problem as they reported above.

Another workaround might be to add `altair<5` to your `requirements.txt`, as discussed at https://discuss.streamlit.io/t/modulenotfounderror-no-module-named-altair-vegalite-v4/42921/6, while it works with `@stlite/desktop` as well.

**Comment by colasajee** [comment]
Thank you all. Everything works as expected with stlite 0.31.0

**Comment by GVanave** [comment]
pip install altair==4 can also solve the same issue
