### ISSUE TITLE
`backticks`: can they be used inside app code?

### ISSUE THREAD

**Issue by robna** [whitphx/stlite#612]
I am trying to run a streamlit app with stlite which includes some `st.markdown()` with text enclosed in backticks to highlight code when the markdown is rendered.
Backticks, however, are also used to enclose the whole python code:

```html
...
<script>
      stlite.mount(
`
# python code for the app
`,
        document.getElementById("root")
      );
    </script>
  </body>
</html>
```
So using them inside the app (like in the markdown example) would signal an end of the mounted code.
Is there a way that backticks could be used inside the app, or is it just not possible?

**Comment by robna** [comment]
One idea:  in order to avoid having backticks directly inside the `stlite.mount()`, would it be possible to **not** include the app code directly, but import it?

Something like this:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>stlite app</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@stlite/mountable@0.34.0/build/stlite.css"
    />
  </head>
  <body>
    <div id="root"></div>
    <script src="https://cdn.jsdelivr.net/npm/@stlite/mountable@0.34.0/build/stlite.js"></script>
    <script>
      stlite.mount(
        `
from app import main
main()
`,
        document.getElementById("root")
      );
    </script>
  </body>
</html>
```
It gives an error [1], as it can't find the `app.py`, which is located in the same directory. (it neither works with using `from .app import main`, see error [2])

<details>
<summary>error 1</summary>
<code>
ModuleNotFoundError: No module named 'app'
Traceback:
File "/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 557, in _run_script
    exec(code, module.__dict__)
File "/home/pyodide/streamlit_app.py", line 2, in <module>
    from app import main
</code>
</details>
<details>
<summary>error 1</summary>
<code>
ImportError: attempted relative import with no known parent package
Traceback:
File "/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 557, in _run_script
    exec(code, module.__dict__)
File "/home/pyodide/streamlit_app.py", line 2, in <module>
    from .app import main
</code>
</details>
I notice from the tracebacks that it is not running it using the venv, which I created for the project, and which I use when I run the app without stlite (i.e. using `streamlit run app.py`)

This is how the project directory looks like:
```
# project
# |__ data            # contains some data and media files loaded by the app
# |
# |__ __init__.py     # empty
# |__ index.html      # stlite html template containing st.mount(`from app import main; main()`)
# |
# |__ app.py          # main streamlit app code
# |__ functions.py    # functions imported by the app
```
I can start stlite in the browser by calling `python -m http.server` from inside the project directory. Opening a browser on 0.0.0.0:8000 starts to load stlite, but then throws the import error. Opening the index.html itself in the browser, leads to the same result.

**Comment by whitphx** [comment]
Hi, there are 2 answers:

## Escape the backticks
Inside a JS string literal starting and ending with backticks, you can use backticks with escaping with `\`.
The example is below.
```html
    <script>
      stlite.mount(
        `
import streamlit as st

st.markdown("This is an inline code format: \`code\`")
`,
        document.getElementById("root")
      );
    </script>
```

### Import external files
The second approach you tried is possible as described in this section of README:
https://github.com/whitphx/stlite#passing-an-object-with-a-url

**Comment by robna** [comment]
ok, escaping seems like an easy-enough option.
