### ISSUE TITLE
Add option to use a custom Pyodide distribution

### ISSUE THREAD

**Issue by dmenezesgabriel** [whitphx/stlite#614]
It would be nice to be able to use a custom Pyodide distribution like in jupyterlite: https://jupyterlite.readthedocs.io/en/stable/howto/pyodide/pyodide.html.

**Comment by whitphx** [comment]
Thank you for the request!
I think it's easily possible.
Can you let me know your use case as a reference? Do you build custom Pyodide distros for your project usually?

**Comment by dmenezesgabriel** [comment]
Actually my company has a restrictive policy to cdn access, wich makes use pyodide via cdn not possible. But using tools like Jupyterlite and Stlite to upskilling business team members and also teach new developers would be a very rich experience in our cenary, Im preparing a material do deploy in jupyterlite already.

Thank you for the response!

**Comment by whitphx** [comment]
I released `@stlite/mountable` v0.39.0 with the `pyodideUrl` option as documented [here](https://github.com/whitphx/stlite#different-pyodide-distributions).
Is it enough for your purpose?
Please check it, thanks!

**Comment by whitphx** [comment]
Good!

**Comment by whitphx** [comment]
Don't you use [stlite sharing](https://edit.share.stlite.net/) btw?
