### ISSUE TITLE
Using different Pyodide version with stlite desktop

### ISSUE THREAD

**Issue by ineporozhnii** [whitphx/stlite#649]
Could you please tell me if it is possible to use a different Pyodide version with stlite/desktop? 

I want to use Pyodide Version 0.23.4 instead of Stlite default 0.23.3, since it re-enabled support for sparseqr, freesasa, lightgbm, opencv-python, and wordcloud

**Comment by whitphx** [comment]
Sorry it's not been answered.

* It's not officially supported. Pyodide's API and its file structure are changed in each version and stlite can't support all different versions.
* Instead, you can download a specific version of Pyodide from [its release page](https://pyodide.org/en/stable/usage/downloading-and-deploying.html#github-releases) and replace the `build/pyodide` directory contents with it after running the `dump` command.
