### ISSUE TITLE
pyarrow mock gives runtime error when plotting dataframe

### ISSUE THREAD

**Issue by andeplane** [whitphx/stlite#662]
If I want to do a line chart with data in a pandas dataframe, it crashes with `RuntimeError: The pyarrow package must be version 11.0.0 or greater. Found version 0.0.1`, see the [following example](https://edit.share.stlite.net/#!ChBzdHJlYW1saXRfYXBwLnB5EuMEChBzdHJlYW1saXRfYXBwLnB5Es4ECssEaW1wb3J0IHN0cmVhbWxpdCBhcyBzdAppbXBvcnQgcGFuZGFzIGFzIHBkCmZyb20gUElMIGltcG9ydCBJbWFnZQoKZGF0YV9wb2ludHMgPSBbeycyMVBUMTAxOS4yMXB0MTAxOV90ZW1wZXJhdHVyZV9yZWFkaW5nJzogNTAuMH0sIHsnMjFQVDEwMTkuMjFwdDEwMTlfdGVtcGVyYXR1cmVfcmVhZGluZyc6IDM1LjB9LCB7JzIxUFQxMDE5LjIxcHQxMDE5X3RlbXBlcmF0dXJlX3JlYWRpbmcnOiAyMC4wfSwgeycyMVBUMTAxOS4yMXB0MTAxOV90ZW1wZXJhdHVyZV9yZWFkaW5nJzogNDAuMH0sIHsnMjFQVDEwMTkuMjFwdDEwMTlfdGVtcGVyYXR1cmVfcmVhZGluZyc6IDEwLjB9LCB7JzIxUFQxMDE5LjIxcHQxMDE5X3RlbXBlcmF0dXJlX3JlYWRpbmcnOiA4MC4wfSwgeycyMVBUMTAxOS4yMXB0MTAxOV90ZW1wZXJhdHVyZV9yZWFkaW5nJzogMjUuMH0sIHsnMjFQVDEwMTkuMjFwdDEwMTlfdGVtcGVyYXR1cmVfcmVhZGluZyc6IDY1LjB9LCB7JzIxUFQxMDE5LjIxcHQxMDE5X3RlbXBlcmF0dXJlX3JlYWRpbmcnOiAzNC4wfV0KZHBfZGYgPSBwZC5EYXRhRnJhbWUuZnJvbV9kaWN0KGRhdGFfcG9pbnRzKQpzdC5saW5lX2NoYXJ0KGRwX2RmKQoS1wIKGHBhZ2VzL_Cfjohfc3VicGFnZS5weS5weRK6Agq3AmltcG9ydCBzdHJlYW1saXQgYXMgc3QKCnN0LnRpdGxlKCJTdWIgcGFnZSIpCgpzdC5tYXJrZG93bigiIiIKX3N0bGl0ZV8gc3VwcG9ydHMgKipNdWx0aSBQYWdlIEFwcHMgKE1QQSkqKiwgb2YgY291cnNlIQoKQ3JlYXRlIGBwYWdlcy8qLnB5YCBsaWtlIHRoaXMgZmlsZSB0byBhZGQgbmV3IHBhZ2VzLgoKSWYgeW91IGFyZSBuZXcgdG8gTVBBLCByZWFkIHRoZSBvZmZpY2lhbCB0dXRvcmlhbCBhYm91dCBpdCBb8J-UlyBoZXJlXShodHRwczovL2RvY3Muc3RyZWFtbGl0LmlvL2xpYnJhcnkvZ2V0LXN0YXJ0ZWQvbXVsdGlwYWdlLWFwcHMpCiIiIikKEs0aCg1kYXRhL2xvZ28ucG5nErsaErgaiVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAABmJLR0QA/wD/AP+gvaeTAAAM7UlEQVR42u2da2wU5xWG3QSSoKo0SSuK0uZCaJWEqKWtC1QqVFaLwHNZ27tma4gC4WoIQXIQhNv6MipVRH9UCpBKdapGFX/SGGNKIGlJ2oYEpIaGVumPACFNSpQqIdyJsdc2tqdndrmY9YX17uzufDPPIx1ZiChY873nm3POvPNNUREAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAPuajrYyXmXDTNNW2GsbBV0yZwVcD3fB4KffWiYfxeolvCTonDkhDr46HQPVwp8B1tZWV3iciPDSD81OiReF2SYcEZTRvNlQN/lD2G8bc0xJ8a7RIvtJmmbpeUjOAqgqrin56B+FPjhPQNz0jPUMwVBdUS4EUXEuC6fqHVNK0Ow7ifqwuexqnjL5cydg6iR+4IBySq6RfAm82vYSzKkfhTIy6N8+5Ww4jaxcUjufLgjfJH1/flKQH6xhlJhEYZu05lBaBgxHX93stjTbuAkegX5PnCOFYE8l3+xAos/gH7hVNlZV9idSAf058jHkqA6/oFSYQmeb4Qol+A3Oz+odAkj4o/NU7TL0Auyp8tiiRA33iXfgGyxrEtJJ7cqpcA9Avgwu4vtbXC4qdf8OSualk3SZTYDQ0bJRolfiV/rrBXrhzlwfKnyUcJ0Dc+kYdtm+kX8i3+urpvi9gPiejtAeKC/N3zieSQJCn075pj64P3+oXS0vtQaG53/u9LnB9E/Knxkfy3T9u1tQ8VbPfX9cUBED/9Ql7EX109UkT9fpriT4237fr6GkmIMfn8nUUQbwQsAQbuF3h/wZXdf16G4u8bl+T/s0eSoSrX/cJl60NvgBOAfsHlBNjnQgKk9gvbJBlCdjR6cw7Kn1qET7/gjvhjsXtFsD0uJ0Df+FhisyTEd10rf0zzKGIfMrrFHbtXYq6USLeh8qESoL4+lkPxp8a78u+ttTds+Fqmv2+7aU5G4MOKT52jYVD6YAnQ0HAkjwmQDMvqlp+vJXqP1au/OMzZ/1ZEnVGsRu395/6T8i7+/slwPtEvWNZ0u6joC0P+vvKEVBbyJGLObIzarutTUP31ze+WgifAQP1CXd3EAXd/f1kfChF7UP018Y+QOOGxBBiyX/Cx9SFf0SVTuVtQf7L5DXlY/P36hZ5YbJl4/+OIOLs4r2njUX/yDtCkRAL0id7aWvvSihV2fM4cxJxhOEdHIn7LGi3RrloCXJcM69fbXUuX2u2VlQg73TDNz240aAhKAixWWfyp0bNmjd25aJHdVlGByIcIeSXzOWqf5Oz/DT8lQN/oXrnS7pg3z74YCiH6lPjcMKYhfsf6UF/f69cEoF8YNI5T/iTLn1q/i79fMmzYEPh+QUxyG6l9CmV9oF8ofPkTCj2I+C1rcpDFH+B+4S22/uTuvxXhB69faNX1JxC/89qjZZ1E8IHrF7qcjwaSAKpYH7zUL6xebXcuWGC3KVwiyex/F7WPotYHz9wVYjG747HHVJ3+zEL8lnW7LGQcMWcXnYsXq5YA58X9OYoEqK9fgoBdiPp6u72qSqXyp5HaJ3kHeBMBuzQ6ffJJlWb/HJUip7eNC4L1IZ93AXFVYn3A+hDcaAuHVSh/fk7tk3z49R6idTkBysu9X/6Ulj6A+OvqpiBYl0ei69apMPr8O1t/svx5FtG6G13LlqlQ/ixH/MkTn08hWnejfdYsrA+KzP7LEazL1oi1a1XY/f9I7ZMsf5oRrctPguU9AgWcn5WIf+3aL6t+6gPjz4zirK1pt5IAllWNYN1/eUaB8uc31D7J2f9+ROtuJN4c8/rsX9N+hPgt6z6sDy5HXZ3n3wk4ZZj2Dr3yULNeWbM7yFMgSYB6ROtuOK9Len33f8colwSIXIkOSYTdLUY42hS0w3AlAY4iWndDhXeF/6xX9E2APlF5Vn5u22FUTve9OU7E/0ME6/47wl4X//8S5U8knTi+Q6vc1DQz+k2/Nr+/RrQuWx/kBXmvJ8A/ri9/0gyf9QtYH4JpfZDzPu2Xhi3+iP/6BSl/KhBs8KwPH+ihbMTfv1/QIo0tpeGpyvULsmA7EG3wrA/7B21+sw51+gV73bo75A7QgWiDZX04L7EzN+JXq1+QB19LEWzwrA9HXC1/FO4XZPc/gGiDZ334a+7KH3X6BawPQbY+RDwRLXr4qPy0dmoV4wtR/jQg2sBbH7wSvTuMyMstZnhiPu8AxxBt8KwPf9LDXkyAKxGX8ij3Z5LKoVfjEWzwrA8fGyEvi/9qw5zzO4Hs/qWINojWhwoVEsDpDfbmOgGmI1qsDx6OnpYZ4TG5TICxsmg9CNe9D+h53vqgRvlz7S6ghX+S67vAq4g3ONaHA3qFUgngvIeQ2wSoq/seNgiXrA8e/3TqOZn971RJ/BJNoei4fDwLiPIFmCBYH8rU2v31yLF8Pg/4jsQengr72foQVioBmo3K+kJYI74hSVAjP99B2FgfCvlUuCDWiJT+4GFJhE0SJxC62taHf6tW/hiR/d5xi0ajNyeeGVjWNomLiB7rQx6mP9XefHcgeW7oPFn41+gXVDn1IaRa+dPZEg5/xftvksVid0sSrA3yWUJKWB/0ctUSoFm9l+qv9AsNDZ9hfcD6kKUHqFzd0yX69gsNDW1YHwobH6pX/pzxzXGMfu8XOhcu9L71wVDL+iDvDD/rz1PnrvQLPvrsKtaHnCTAlCK/I/1CsQhos8r9ghLWB0O52f/7gfo6vcr9QsfcuZz64HZokbqioJLSL2B9yDJO6upZH+Th1/1FQUe+UTvVqa0db71ztibWh2BYH2T0+WYRFBXJh9oa+y5kezSa+Lq688QV60P68Ypi1gd582tJ4MUvPcEtsninB1tUR3jO7uuUIFgfhrA+qFf+xHdWVNzO7m+as9JZ4LaysoT/3pnE5LtfwPqQk+nPdmqfZPmza7iL7ZzAnOgX1q3D+qCo9UESoCzw4r8wc+adsoCd2Sz+1X4hFsuN9eGppxQ49aFMtdHn6cB9iXLA3V/Xn3BNCKZpxx95xPV+QQXrw37lTn2IbKX2EWTx3sqFINrKy+3O+fPt7lWrsuoXep3Zv/QeWB+wPrhf/pjmt2QBe3MtkPZIxO5asiSjfkGFM3+Usz7okffY+pPTn435Fku8qsq+tHx5Wv1C1+OPe178Slof9Egts38xP8n054OCCUf6hY5HH7W7a2r69QuO39/5OxXEr6L1IS+HXnne+mAY0zwjJPH3OJOk+OzZnrc6K/LBC6wPacz+n1NJaJz64FospvwpKblNFu8cAg7EBy+wPgyw+0cRcPZx0FCt+a1sovZxZv+6/hICzi4uyOx/l2qzf60yRPMrBx9la30gxPqgh7A+KDr7X4GAA2h90CJbqH2S1oeDCDhb64OhnPVhR2lkEtaHPFkf/B6H+eCFstOfXyDg7OMv6n3wIsbsX6wPsngfIuAsrQ8G1gc1d39d/zECdsH6oF75s4/aJzn9+S0CDuIHLyKLKH+S5c8JBIz1IZC0l5ffjYCDZ30Q5+eL1D7Xxp+IOLuI7zXCsx0/jfMpIUUSwET919yflxBxFu84G8ZVI9kew7jD+ZiciOxA4mxNbybAycbi6pGo/9oT4JcRchYJYJoDGsmaSqMPiNgsif947KX3zai+bx+g61NkIXsQc0Zx0i4uvuFuutOoKHaE5xjPPJAAP0D1/e8CqxBzRuXPsM7QeUXTbnWsx5f7hS5OffCWHWK2LOonCHsYx7qY5uRMr3dB+gUtsgGl36gp1vW5EntlgbsR+ZCnVxx167o3hyofzEO/gPVhOMipa3fJItfIYh9C8AOWP64bySzLuqmlNDw1F/2CnPf/OqrOtDwKhR4Wy4QlC/9fxJ+I3ngolNPdVN7SGiVJUCXi3SNxyYUEmIeSsy2RZIdyPpnkfDVGdsDWwCaArufVSNYyIzxG7go1IuS3M0yAI8z+3U4G2aESp0iY5u6gPUyT5C+YkazFCD8kgn5a4qM0T3w422KGJ6LY/PQL/wyC9eGcB4xkTr+w3ZxVIiJ/vlkPXxgkAQ42adEJKLQw/cJxnyaA54xkTr8g/p5yEfwvpW9odCZK241Z05wkQZH0C+6WP7qOkQwC2y+kZX0A8Ge/YJoYycDdfkGEtUkVC4aUPxjJILD9AkYyCG6/IImJkQzyi7gtv57oF0zzX363PgCk2y98WoAEwEgG3ukXRJDT5a6wLV/9gvw7C7ny4PV+odvP1geAwvQLuv4Hri4ohZQsxSLcZ1w59c40f8oVBTVLpJKSEXJsiS5CfkGiPYMEeJWrCL7gjKaNlt18gTPRSfMYmCNyFxnLlQPfITP9eyQZ1ovIDw8gfOfh2+8uzJx5J1cKfE+rpk2QnX6+czaSfCvhZ60zZozhqgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgB/5P58WvRSYZ4lmAAAAAElFTkSuQmCC)

```
import streamlit as st
import pandas as pd

data_points = [{'21PT1019.21pt1019_temperature_reading': 50.0}, {'21PT1019.21pt1019_temperature_reading': 35.0}, {'21PT1019.21pt1019_temperature_reading': 20.0}, {'21PT1019.21pt1019_temperature_reading': 40.0}, {'21PT1019.21pt1019_temperature_reading': 10.0}, {'21PT1019.21pt1019_temperature_reading': 80.0}, {'21PT1019.21pt1019_temperature_reading': 25.0}, {'21PT1019.21pt1019_temperature_reading': 65.0}, {'21PT1019.21pt1019_temperature_reading': 34.0}]
dp_df = pd.DataFrame.from_dict(data_points)
st.line_chart(dp_df)
```

The mocking of pyarrow doesn't seem to work as intended.

**Comment by andeplane** [comment]
Duplicate https://github.com/whitphx/stlite/issues/656

**Comment by andeplane** [comment]
Seems to work after https://github.com/whitphx/stlite/pull/663

**Comment by whitphx** [comment]
This should be fixed with a new release, 0.42.4.
It pins the altair version to <5.2.0 as a workaround.

Plz wait more for a long-term solution fixing the pyarrow mock versioning and allowing altair>=5.2.0 to be installed.

**Comment by LukasMasuch** [comment]
@whitphx `altair>=5.2.0` is also now allowed with the latest version of stlite or?

**Comment by whitphx** [comment]
Sorry missed this.
Yes, it should be working on the latest stlite, thanks.
