### ISSUE TITLE
stlite Desktop Errors: no such file or directory "stlite-manifest.json"

### ISSUE THREAD

**Issue by weissenbacherpwc** [whitphx/stlite#669]
Hi,

when doing the [stlite Desktop tutorial](https://github.com/whitphx/stlite/blob/main/packages/desktop/README.md) to convert my Streamlit application to a desktop application I am facing several errors. 
First of all when trying to `npm run dump streamlit_app -- -r requirements.txt` I am facing this error with almost every package in my `requirements.txt file`:
`Can't find a pure Python 3 wheel for 'sentence-transformers==2.2.2'`

When ignoring additional packages (`npm run dump streamlit_app`) and trying `npm serve` I am getting this error: `no such file or directory "stlite-manifest.json"` and the app is not building.

I am using:
- python 3.11.5  
- I made sure to use the most recent electron version:
`{
    "name": "rag_stlite_app",
    "version": "0.1.0",
    "main": "./build/electron/main.js",
    "scripts": {
      "dump": "dump-stlite-desktop-artifacts",
      "serve": "cross-env NODE_ENV=production electron .",
      "servewindows": "electron .",
      "pack": "electron-builder --dir",
      "dist": "electron-builder",
      "postinstall": "electron-builder install-app-deps"
    },
    "build": {
      "files": ["build/**/*"],
      "directories": {
        "buildResources": "assets"
      }
    },
    "devDependencies": {
      "@stlite/desktop": "0.42.4",
      "cross-env": "^7.0.3",
      "electron": "^28.1.1",
      "electron-builder": "^24.9.1"
    }
  }`

So is this tutorial up-to-date or what am I doing wrong?

**Comment by whitphx** [comment]
Let me close this issue. Plz reopen it or report to me if you still have a problem.
