### ISSUE TITLE
Question - but packaging==23.1 is already installed

### ISSUE THREAD

**Issue by tomer-ben-david** [whitphx/stlite#684]
Hi,

I run:

```
npm run dump streamlit_app -- -r requirements.txt
```

My requirements.txt has:

```
packaging==23.2 ; python_full_version >= "3.11.0" and python_full_version < "4.0.0"
```

I get error:

```
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 235, in check_version_satisfied
    raise ValueError(
ValueError: Requested 'packaging==23.2; python_full_version >= "3.11.0" and python_full_version < "4.0.0"', but packaging==23.1 is already installed
```

How to tell the commend npm run dump to use the versions from my requirements.txt and override with them?

**Comment by whitphx** [comment]
Pyodide provides `micropip` as a package manager and stlite also uses it to install the required packages, as `micropip.install()` must be used to install packages.
It seems that `micropip` depends on `packaging` so the specific version of `packaging` is installed when `micropip` is loaded, which is mandatory to use `micropip.install()` anyway.

I don't know the solution for it, how to load a specific version of `packaging` when loading `micropip` (`pyodide.loadPackage(["micropip"])`).
Please ask Pyodide's team for this question. -> https://github.com/pyodide/pyodide

**Comment by whitphx** [comment]
Let me close this issue. Plz reopen it or report to me if you still have a problem.
