### ISSUE TITLE
How to use "loadPyodide({ fullStdLib : true })" setting.

### ISSUE THREAD

**Issue by terapyon** [whitphx/stlite#737]
I'm trying to make a desktop app using sqlite3.
But I got an error at `import sqlite3`.
I checked the document https://pyodide.org/en/stable/usage/wasm-constraints.html#optional-modules.
Do you have any idea how to setup "loadPyodide({ fullStdLib : true })" on package.json or support the option?

**Comment by whitphx** [comment]
You should add `sqlite3` to your requirements list e.g. `requirements.txt` to use it in your app.
Currently passing such a config to `loadPyodide` is not supported, but you can install such unvendored standard libs just like third-party packages.

**Comment by whitphx** [comment]
Let me close this issue. Plz reopen it or report to me if you still have a problem.
