### ISSUE TITLE
internet with the desktop application

### ISSUE THREAD

**Issue by SzymonFabian** [whitphx/stlite#762]
Hi,

is it possible to load data from the internet with the desktop application?

I have this type of error:
AttributeError: module 'http.client' does not have attribute 'HTTPSConnection'
Traceback:
File 'streamlit/runtime/scriptrunner/script_runner.py', line 542, in _run_script
File '/home/pyodide/streamlit_app.py', line 13, in
db = deta.Base("XXX")
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/lib/python3.11/site-packages/deta/init.py", line 43, in Base
return _Base(name, self.project_key, self.project_id, host)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/lib/python3.11/site-packages/deta/base.py", line 76, in init
super().init(
File "/lib/python3.11/site-packages/deta/service.py", line 27, in init
self.client = http.client.HTTPSConnection(host, timeout=timeout) if keep_alive else None

**Comment by whitphx** [comment]
Yes, it's possible but there are some things you have to know.
See the bullet point starting with "Networking libraries .." in https://github.com/whitphx/stlite?tab=readme-ov-file#limitations
