### ISSUE TITLE
Can't find a pure Python 3 wheel for

### ISSUE THREAD

**Issue by Xaego** [whitphx/stlite#785]
'pypylon~=3.0.1', 'streamlit~=1.30.0', 'pyautogui~=0.9.54
', 'opencv-python~=4.9.0.80', 'scipy~=1.11.4', 'pandas~=2.0.1', 'numpy~=1.26.0'

**Comment by whitphx** [comment]
See the last item of https://github.com/whitphx/stlite?tab=readme-ov-file#limitations
