### ISSUE TITLE
Redesign `@stlite/desktop`'s dump command API

### ISSUE THREAD

**Issue by whitphx** [whitphx/stlite#853]
* Its options which we are now passing as command line args, e.g. the app directory and the requirements, should be defined in `package.json`.
    * Such file-based build config is more consistent and useful.
* Support an arbitrary entrypoint name.
* Support `-p` option like `tsc` to specify the project root dir where `package.json` exists. It's not fixed to `process.cwd()`.

We should keep the current `dump` command marking it deprecated and create a new one for the compatibility.

**Comment by terapyon** [comment]
"e.g. the app directory" : Does this mean that we can use another app name for "streamlit_app"? If yes, it is very very useful. If no set for app name in package.json, to expect using streamlit_app.py.

**Comment by whitphx** [comment]
Thank you. Yes, I plan to allow any app name by such settings.
