### ISSUE TITLE
joblib file

### ISSUE THREAD

**Issue by nusratkhowaja** [whitphx/stlite#904]
is this support import joblib

**Comment by nusratkhowaja** [comment]
ModuleNotFoundError: The module 'joblib' is included in the Pyodide distribution, but it is not installed. You can install it by calling: await micropip.install("joblib") in Python, or await pyodide.loadPackage("joblib") in JavaScript See https://pyodide.org/en/stable/usage/loading-packages.html for more details

**Comment by nusratkhowaja** [comment]
trying to load as await micropip.install("joblib"); any suggestions

**Comment by whitphx** [comment]
Provide the details of your app, including the env, the source files, `requirements.txt`, etc with which I can reproduce the problem.
