### ISSUE TITLE
how can i load model.pkl file from my root directory.

### ISSUE THREAD

**Issue by nusratkhowaja** [whitphx/stlite#905]
with open("pipeline_grid_xgb.pkl" ,'rb') as f:
    pipeline_grid_xgb = load(f)

this is not loading my model :( please help

**Comment by whitphx** [comment]
Are you trying to access your local files from the stlite app?
If so, you should read this section: https://github.com/whitphx/stlite?tab=readme-ov-file#file-system

**Comment by nusratkhowaja** [comment]
thnaks for reply , i am still  having an issue : FileNotFoundError: [Errno 44] No such file or directory: '/mnt/pipeline_grid_xgb.pkl'
here is three 

├── mnt
│   └── pipeline_grid_xgb.pkl



        stlite.mount(
  {
    requirements: ["joblib","plotly",], // Packages to install
    idbfsMountpoints: ["/mnt"], // Mount the IndexedDB-based file system to the /mnt directory.
    entrypoint: "app.py", // The target file of the `streamlit run` command
    files: {
      "app.py": `

import streamlit as st
import pandas as pd
from joblib import load
import plotly.express as px
import os

# Load the joblib file from the mounted directory
with open("/mnt/pipeline_grid_xgb.pkl", 'rb') as f:
    pipeline_grid_xgb = load(f)
