### ISSUE TITLE
stlite Desktop Errors: no such file or directory "stlite-manifest.json" 

### ISSUE THREAD

**Issue by slowflower** [whitphx/stlite#958]
Hi,

when doing the [stlite Desktop tutorial](https://github.com/whitphx/stlite/blob/main/packages/desktop/README.md) to convert my Streamlit application to a desktop application I am facing an error.
Essentially, `npm dump `does not create a `stlite-manifest.json` file: 

> (node:199364) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'D:\python_projects\streamlit_app\build\stlite-manifest.json'
> (Use `electron --trace-warnings ...` to show where the warning was created)
> (node:199364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

i am using following package.json, tried also with version 0.57.0 of @stlite/desktop:
```
{
  "name": "streamlit_app",
  "version": "0.1.0",
  "main": "./build/electron/main.js",
  "scripts": {
    "dump": "dump-stlite-desktop-artifacts",
    "serve": "cross-env NODE_ENV=production electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder",
    "postinstall": "electron-builder install-app-deps"
  },
  "build": {
    "files": [
      "build/**/*"
    ],
    "directories": {
      "buildResources": "stlite"
    }
  },
  "devDependencies": {
    "@stlite/desktop": "^0.58.0",
    "cross-env": "^7.0.3",
    "electron": "30.0.8",
    "electron-builder": "^24.13.3"
  },
  "stlite": {
    "desktop": {
      "files": [
        "app.py"
      ],
      "entrypoint": "app.py",
      "dependencies": [
        "yfinance",
        "numpy",
        "pandas",
        "matplotlib",
        "streamlit-option-menu",
        "forex_python"
      ],
      "requirementsTxtFiles": [
        "requirements.txt"
      ]
    }
  }
}
```

**Comment by whitphx** [comment]
@slowflower Hi, thank you for the report, but unfortunately I couldn't reproduce it.
Can you provide a whole repo and env info?
